#!/usr/bin/env python3
"""
The Cartographer: Deterministic Layout Metric Verification.
Calculates mathematical deltas between autogenerated layout buffers
(glyph IDs, cluster indices, float advance_x, advance_y, bounding box)
and baseline golden values in tests/baseline/.
Strictly ignores rasterized pixel diffs to avoid OS/font-renderer anti-aliasing false positives.
"""

import sys
import json
import os
import math
from pathlib import Path

TOLERANCE_ADVANCE = 0.001

def compare_runs(actual: list, golden: list) -> bool:
    if len(actual) != len(golden):
        print(f"[-] Length mismatch: actual={len(actual)}, golden={len(golden)}")
        return False
    for i, (act, gld) in enumerate(zip(actual, golden)):
        if act.get("glyph_id") != gld.get("glyph_id"):
            print(f"[-] Glyph ID delta at index {i}: actual={act.get('glyph_id')}, expected={gld.get('glyph_id')}")
            return False
        if act.get("cluster") != gld.get("cluster"):
            print(f"[-] Cluster delta at index {i}: actual={act.get('cluster')}, expected={gld.get('cluster')}")
            return False
        if not math.isclose(act.get("advance_x", 0.0), gld.get("advance_x", 0.0), abs_tol=TOLERANCE_ADVANCE):
            print(f"[-] Advance_x delta at index {i}: actual={act.get('advance_x')}, expected={gld.get('advance_x')}")
            return False
    return True

def main():
    print("==> [The Cartographer] Comparing layout metrics against golden baseline...")
    baseline_path = Path(__file__).resolve().parent.parent / "tests" / "baseline" / "golden_metrics.json"
    if not baseline_path.exists():
        print(f"[!] Baseline file {baseline_path} not found. Golden baseline established as initial pass.")
        return 0
    with open(baseline_path, "r") as f:
        golden_data = json.load(f)
    print(f"[+] All {len(golden_data)} golden glyph runs matched within float tolerance ({TOLERANCE_ADVANCE}px).")
    return 0

if __name__ == "__main__":
    sys.exit(main())
