#pragma once

#include <cstddef>
#include <cstdint>
#include <span>
#include <concepts>
#include <optional>
#include <string_view>

namespace dungeons::text {

/**
 * @brief Represents an individual positioned glyph inside a shaped run.
 */
struct PositionedGlyph {
    uint32_t glyph_id{0};
    uint32_t cluster_index{0};
    float advance_x{0.0f};
    float advance_y{0.0f};
    float offset_x{0.0f};
    float offset_y{0.0f};
};

/**
 * @brief C++20 Concept enforcing Text Shaping Output Buffer properties.
 */
template <typename T>
concept TextGlyphBuffer = requires(T b, size_t idx, PositionedGlyph g) {
    { b.data() } -> std::same_as<PositionedGlyph*>;
    { b.size() } -> std::same_as<size_t>;
    { b[idx] = g };
};

/**
 * @brief Contract for the Skia/HarfBuzz-based Zero-Trust Text Shaper.
 * Generated by The Architect based on RFC 001.
 */
class TextShaper {
public:
    constexpr TextShaper() noexcept = default;
    ~TextShaper() noexcept = default;

    // Non-copyable, movable
    TextShaper(const TextShaper&) = delete;
    TextShaper& operator=(const TextShaper&) = delete;
    TextShaper(TextShaper&&) noexcept = default;
    TextShaper& operator=(TextShaper&&) noexcept = default;

    /**
     * @brief Shapes a UTF-8 text run into the caller-provided glyph buffer.
     * Guaranteed zero-allocation hot path.
     *
     * @param utf8_bytes Raw byte view of the UTF-8 text stream.
     * @param out_buffer Caller-managed destination span for positioned glyphs.
     * @return std::optional<size_t> Number of glyphs written, or nullopt on malformed stream.
     */
    [[nodiscard]] std::optional<size_t> shape_cluster(
        std::span<const std::byte> utf8_bytes,
        std::span<PositionedGlyph> out_buffer
    ) const noexcept;
};

} // namespace dungeons::text
